name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: connect to remote vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/my-projects/discuss-station
            sudo git pull origin master
            sudo docker build -t discuss-station:latest .
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f
            curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"Bang, berhasil update kode di 'Discuss Station',\n\nCommit Message: ${{ github.event.commits[0].message }}\"}" ${{ secrets.DISCORD_WEBHOOK }}
